[package]
name = "cbsk"
version = "0.1.0"
edition = "2021"
description = "cbsk is a callback socket tool"
readme = "Readme.md"
authors = ["The cbsk developers"]
license = "MIT/Apache-2.0"
categories = ["network-programming"]
keywords = ["socket", "net", "tcp", "ws", "websocket"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#cbsk_socket = { version = "0.3.12" }
cbsk_socket = { path = "libs/cbsk_socket" }

[features]
default = ["client"]
client = ["cbsk_socket/tcp_client"]
server = ["cbsk_socket/tcp_server"]
